---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
data: 
  values.yaml: |
    ingress-controller:
      enabled: true
    dashboard:
      enabled: true
    admin:
      allow:
        ipList:
          - 0.0.0.0/0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix
spec:
  releaseName: apisix
  chart:
    spec:
      chart: apisix
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apisix
        namespace: flux-system
      version: "0.11.3"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: apisix-config