apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix
spec:
  releaseName: apisix
  chart:
    spec:
      chart: apisix
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apisix
        namespace: flux-system
      version: "0.11.3"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: apisix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix
data: 
  values.yaml: |
    dashboard:
      enabled: true
    admin:
      allow:
        ipList: {0.0.0.0/0}
    ingress-controller:
      enabled: true
      config:
        apisix:
          serviceNamespace: apisix
    namespace:
      apisix      
    
