---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-values
data:
  values.yaml: |
    gateway:
      type: LoadBalancer
      ingress:
        enabled: true
        hosts:
          - host: apisix.127.0.0.1.nip.io
            paths:
              - /*      
    ingress-controller:
      enabled: true
      config:
        apisix:
          serviceNamespace: apisix-system
    dashboard:
      enabled: true
    etcd:
      replicaCount: 3
    admin:
      allow:
        ipList:
          - 0.0.0.0/0      
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix
spec:
  releaseName: apisix
  chart:
    spec:
      chart: apisix
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apisix
        namespace: flux-system
      version: "0.11.3"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: apisix-values