apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sources.yaml
  - prometheus.yaml
  - tempo.yaml
  - grafana.yaml
  - redis.yaml
  - dapr.yaml
  - keycloak.yaml
  - kafka.yaml
  - traefik.yaml