apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - sources.yaml
  - dapr.yaml
  - traefik.yaml
  - kafka.yaml
  - mongodb.yaml
  - petclinic.yaml
  - apisix.yaml