apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: petclinic
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: petclinic
  path: ./flux
  prune: true
  wait: true
  dependsOn:
    - name: traefik
    - name: redis