---
apiVersion: v1
kind: Namespace
metadata:
  name: petstore
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: petstore
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: petstore
  path: ./flux
  prune: true
  wait: true
  dependsOn:
    - name: traefik
    - name: redis