apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-values
data:
  values.yaml: |
    allInOne:
      enabled: true
    ingress:
      enabled: true
      labels:
        hosts:
          - jaeger.127.0.0.1.nip.io