apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      reconcileStrategy: ChartVersion
      sourceRef:
        name: jaeger
        kind: HelmRepository
        namespace: flux-system
      version: "0.65.3"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-values