apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      reconcileStrategy: ChartVersion
      sourceRef:
        name: bitnami
        kind: HelmRepository
        namespace: flux-system
      version: "13.4.1"
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
data:
  values.yaml: |
    architecture: replicaset
    replica:
      replicaCount: 0
    auth:
      enabled: false      