apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: "9.3.2"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values