apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        name: traefik
        kind: HelmRepository
        namespace: flux-system
      version: "20.5.2"
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values