apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        name: bitnami
        kind: HelmRepository
        namespace: flux-system
      version: "17.3.14"
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: redis-values